[workspace]
resolver = "3"
members = ["branches", "enums", "error_handling", "fearless_concurrency", "functions", "guessing_game", "loops", "minigrep", "playground", "rectangles", "restaurant", "variables"]
